### ISSUE TITLE
Some users don't appear on the Contributors page

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/repostatistics#10]
I don't know what the problem is, but my user doesn't appear on the [Contributors Page](http://asrob.uc3m.es/contributors/) .

This can also mean that other users can have this problem too.

**Comment by David-Estevez** [comment]
Thanks for the report! I have just checked it and, more precisely, none of the ASROB users that are placed in the second page of the "people" section(see attached image)  appear on the ranking. 

![image](https://cloud.githubusercontent.com/assets/1451819/25146912/f32e8b20-2475-11e7-973f-3d5092d459a2.png)

Only 30 members appear on the [Contributors Page](http://asrob.uc3m.es/contributors/) and there are 30 members per page, so I assume pagination must be the cause for this issue. Probably if new members are added to the list, the list will change and different user will be left out of the  [Contributors Page](http://asrob.uc3m.es/contributors/). I'll check it and fix it as soon as possible.

**Comment by David-Estevez** [comment]
Added alert to webpage to inform of this issue to users while we are trying to solve it:
![image](https://cloud.githubusercontent.com/assets/1451819/25205742/78eab8c6-2564-11e7-9a9a-1783fa3887ec.png)

**Comment by David-Estevez** [comment]
@PeterBowman fixed this at #14, I'm now updating the server with the new code.
