### ISSUE TITLE
Add 'last modified' notice with timestamp

### ISSUE THREAD

**Issue by PeterBowman** [asrob-uc3m/repostatistics#18]
As found out in #17, the script may crash without anyone noticing it at all. Apart from that, timestamps feel like a necessary addition for any type of periodically generated data (which obviously changes over time).

**Comment by jgvictores** [comment]
Good idea! Doxygen, for instance puts a `Generated on Tue Dec 5 2017 00:30:16 by Doxygen vX.X.X` at the bottom left ([example](http://asrob.uc3m.es/rddoc/index.html)).

**Comment by David-Estevez** [comment]
Done at https://github.com/asrob-uc3m/repostatistics/commit/ab43e7c8ef7e4abb7848612d9f41292b1879bb74, updating server right now!

BTW, great idea! I'm implementing it on all the remaining generated pages. :blush:
