### ISSUE TITLE
Contributors of a forked repo are taken into account

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/repostatistics#2]
When running the script againts a github organization with forks, the script takes into account the commits of the forked repo.

Some solutions I think of are:

* Ignoring forks
* Adding colaborations from organization members only

@jgvictores what do you think?

**Comment by jgvictores** [comment]
Ideally... Switch by parameter, including the possibility of manually specifying! 😊

**Comment by David-Estevez** [comment]
As current version retrieves information based on members belonging to the organization, contributions from foreigners (even in forks belonging to the organization) are not taken into account.

This mean we have only available solution 2 from the proposed ones but I think it will suffice.
