### ISSUE TITLE
GitHub users vs team repostatistics

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/repostatistics#4]
The current [repostatistics.py](https://github.com/asrob-uc3m/repostatistics/blob/9b914d90d7e8475c30a3bd8e8eff6fce8b374465/repostatistics.py) is oriented at extracting commits per GitHub user. However, if we want to see the throughput of a team (or active work group) as a whole, this has to be manually computed.

Not sure if this could be set through parameter or requires a whole new script.

**Comment by jgvictores** [comment]
Additional parameters on the team repostatistics could be to ponderate by dividing between number of members (or active members, senior members (?), etc...).

**Comment by David-Estevez** [comment]
This is an example of the kind of parameters I was asking in #3 

I have to check it out, but in principle as long as the different work groups are updated in the github organization, it should be possible to extract that information too.

**Comment by jgvictores** [comment]
Closing, now listed as parameter in #3.
